# docker-compose version
version: "2"

services:
  # service 이름
  zookeeper:
    # 컨테이너 이름
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      # 토픽 생성
      # 토픽 이름:Partition 개수:Replica 개수
      # Partition: Topic을 분할한 단위, 전체 topic 메세지 순서는 보장할 수 없지만, partition 안에서 메세지 순서는 보장
      # Replica: 장애가 났을 때를 대비해서 복제본을 만들어놓고 운영하는 방식
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
      # zookeeper 정보
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
